DELETE FROM USERS_FRIENDS;
DELETE FROM USERS;
DELETE FROM FILMS_GENRES;
DELETE FROM FILMS_LIKES;
DELETE FROM FILMS;

COMMIT;

ALTER TABLE FILMS ALTER COLUMN id RESTART WITH 1;
ALTER TABLE USERS ALTER COLUMN id RESTART WITH 1;
--
-- INSERT INTO users (LOGIN, EMAIL, NAME, BIRTHDAY)
-- VALUES ('loginname', 'email@email.ru', 'username', PARSEDATETIME('01.01.1990', 'dd.mm.yyyy'));