-- Insert initial data about genres and ratings of mpa
INSERT INTO RATINGS_MPA (NAME) VALUES ('G');
INSERT INTO RATINGS_MPA (NAME) VALUES ('PG');
INSERT INTO RATINGS_MPA (NAME) VALUES ('PG-13');
INSERT INTO RATINGS_MPA (NAME) VALUES ('R');
INSERT INTO RATINGS_MPA (NAME) VALUES ('NC-17');

INSERT INTO GENRES (NAME) VALUES ('Комедия');
INSERT INTO GENRES (NAME) VALUES ('Драма');
INSERT INTO GENRES (NAME) VALUES ('Мультфильм');
INSERT INTO GENRES (NAME) VALUES ('Триллер');
INSERT INTO GENRES (NAME) VALUES ('Документальный');
INSERT INTO GENRES (NAME) VALUES ('Боевик');

COMMIT;